# Generated by Django 4.2.2 on 2023-11-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
    ]
