# Generated by Django 4.2.7 on 2023-11-17 19:01

from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('inventory', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('category', models.CharField(choices=[('board_game', 'board_game'), ('card_game', 'card_game'), ('video_game', 'video_game'), ('war_games', 'war_games'), ('adventure', 'adventure')], max_length=20)),
            ],
        ),
    ]
