# Generated by Django 4.2.7 on 2023-11-17 21:20

import decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('92b65201-ec28-4718-b49b-c6ad36363ed8'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('ba96d311-f3c6-4b89-ab01-4c37f021474c'), primary_key=True, serialize=False)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=decimal.Decimal, max_digits=10),
        ),
        migrations.CreateModel(
            name='UserTransactionDetails',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shop.usertransaction')),
                ('order_id', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=decimal.Decimal, max_digits=10)),
                ('category', models.CharField(choices=[('board_game', 'board_game'), ('card_game', 'card_game'), ('video_game', 'video_game'), ('war_games', 'war_games'), ('adventure', 'adventure')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('comments', models.TextField(default=str)),
            ],
        ),
    ]
