# Generated by Django 4.2.7 on 2023-11-17 21:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_usertransaction_purchased_by_store_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.UUIDField(default=uuid.UUID('76a68c9e-f14a-48c4-9aa6-ae7e8922c1c2'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a9903646-e763-4282-8524-6aeb4e3639e7'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usertransactiondetails',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shop.usertransaction'),
        ),
    ]
