# Generated by Django 4.2.7 on 2023-11-22 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(default='10078fcd-9ed8-4c2c-b4a1-d80c2d167919', on_delete=django.db.models.deletion.CASCADE, to='shop.store'),
            preserve_default=False,
        ),
    ]
