# Generated by Django 4.2.7 on 2023-11-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
