# Generated by Django 4.2.7 on 2023-11-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
