# Generated by Django 4.2.7 on 2023-11-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_usertransactiondetails_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image_url',
            field=models.TextField(default=''),
        ),
    ]
