# Generated by Django 4.2.7 on 2023-11-30 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_store_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='image_url',
        ),
    ]
