# Generated by Django 4.2.7 on 2023-11-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_store_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.TextField(default=''),
        ),
    ]
