# Generated by Django 4.2.7 on 2023-12-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_usertransactiondetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransactiondetails',
            name='category',
            field=models.CharField(choices=[('board_game', 'board_game'), ('card_game', 'card_game'), ('video_game', 'video_game'), ('war_games', 'war_games'), ('adventure', 'adventure')], max_length=20, null=True),
        ),
    ]
